### PR TITLE
- Implemented Firebase

### PR DESCRIPTION
**Pull request by huerd**
> - Added Crashlytics
> - Added FirebasePerformance

Did a few crash tests and it works.

image

**Setup**

- [Install Cocoapods](https://guides.cocoapods.org/using/getting-started.html#getting-started)
- Go to your repo directory
- `pod install`
- from here on, launch from `ETS-mobile.xcworkspace`

### CODE REVIEW

**Comment by kovy42** [comment]
What account did you use for Firebase? We might want to have a shared account for the club.

**Comment by Sonphil** [comment]
ApplETS does have an account, so you should use it instead of your own. 🙂

**Comment by howardphi** [comment]
...I didn't even think of that. D'oh. I'm guessing the changes have been made on @kovy42 end and it's good to merge?

**Comment by Sonphil** [comment]
I think you should add GoogleService-Info.plist to .gitignore.

**Comment by kovy42** [comment]
Yep I kind of screwed up on my part anyways, I added the wrong token. Two wrongs make a right. I added it to the gitignore file though.

**Comment by howardphi** [comment]
Re-opening PR

**Comment by howardphi** [comment]
Deleting this branch and creating a new one that'll get merged afterwards.

**Pull request merged**
